<?php
/**
 * Title: HandyList - Default Footer
 * Slug: handylist/footer-default
 * Categories: blockstrap-site-footer
 * Viewport Width: 1280
 */

 $logo_url = esc_url( get_theme_file_uri( 'assets/images/logo-color.svg' ) ); /* <?php echo esc_url( $logo_url ); ?> */

?>

<!-- wp:blockstrap/blockstrap-widget-container {"container":"container-fluid","bg":"light","bg_color":"rgba(136,136,136,0.06)","mb_lg":"","pt":"5","pr":"0","pl":"0","pt_lg":"7","position":"position-relative","anchor":"footer","sd_shortcode":"[bs_container container='container-fluid'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg='light'  bg_color='rgba(136,136,136,0.06)'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt='5'  pr='0'  pb=''  pl='0'  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg='7'  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position='position-relative'  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor='footer'  css_class='' ]","sd_shortcode_close":"[/bs_container]","className":"block-1618467995"} -->
<div class="wp-block-blockstrap-blockstrap-widget-container pt-5 pe-0 ps-0 pt-lg-7 bg-light bg-image-fixed container-fluid position-relative" id="footer"><!-- wp:blockstrap/blockstrap-widget-container {"col_lg":"10","mb_lg":"","pr":"0","pl":"0","sd_shortcode":"[bs_container container='container'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg='10'  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr='0'  pb=''  pl='0'  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]","sd_shortcode_close":"[/bs_container]","className":"block-1618467995"} -->
<div class="wp-block-blockstrap-blockstrap-widget-container pe-0 ps-0 col-10 bg-image-fixed container"><!-- wp:blockstrap/blockstrap-widget-container {"container":"row","mb_lg":"","position":"position-relative","sd_shortcode":"[bs_container container='row'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position='position-relative'  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]","sd_shortcode_close":"[/bs_container]","className":"block-1618467995"} -->
<div class="wp-block-blockstrap-blockstrap-widget-container bg-image-fixed row position-relative"><!-- wp:blockstrap/blockstrap-widget-container {"container":"col","col":"12","col_md":"6","col_lg":"3","text_color":"dark","mb_lg":"","content":"","sd_shortcode":"[bs_container container='col'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col='12'  col_md='6'  col_lg='3'  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_on_text='false'  text_color='dark'  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]","sd_shortcode_close":"[/bs_container]","className":"block-1618467995"} -->
<div class="wp-block-blockstrap-blockstrap-widget-container col-12 col-md-6 col-lg-3 bg-image-fixed text-dark col"><!-- wp:heading {"style":{"typography":{"fontStyle":"normal","fontWeight":"700"},"elements":{"link":{"color":{"text":"var:preset|color|gray-dark"}}}},"textColor":"gray-dark","fontSize":"medium"} -->
<h2 class="wp-block-heading has-gray-dark-color has-text-color has-link-color has-medium-font-size" style="font-style:normal;font-weight:700">Company</h2>
<!-- /wp:heading -->

<!-- wp:blockstrap/blockstrap-widget-nav {"inside_navbar":"0","flex_direction":"flex-column","font_size":"fs-5","mr_lg":"","ml_lg":"n3","sd_shortcode":"[bs_nav anchor=''  inside_navbar='0'  container=''  flex_direction='flex-column'  nav_style=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  nav_fill=''  font_size='fs-5'  font_size_custom=''  bg=''  mt=''  mr='auto'  mb=''  ml='auto'  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg='n3'  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  width=''  css_class='' ]","sd_shortcode_close":"[/bs_nav]"} -->
<div class="wp-block-blockstrap-blockstrap-widget-nav blockstrap-nav" id="navbarNav_"><ul class="wp-block-blockstrap-blockstrap-widget-nav nav me-auto ms-auto ms-lg-n3 flex-column fs-5"><!-- wp:blockstrap/blockstrap-widget-nav-item {"text":"About us","text_color":"gray-dark","font_weight":"font-weight-normal","content":"\u003ca href=\u0022#http://handylist.local\u0022 class=\u0022nav-link link-gray-dark fw-normal\u0022 \u003eAbout us\u003c/a\u003e","sd_shortcode":"[bs_nav_item type='home'  page_id=''  post_id=''  taxonomy=''  term_id=''  custom_url=''  text='About us'  icon_class=''  icon_aria_label=''  link_new_window='false'  link_nofollow='false'  link_attributes=''  link_type=''  link_size=''  link_bg=''  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg=''  link_pr_lg=''  link_pb_lg=''  link_pl_lg=''  link_divider=''  text_color='gray-dark'  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight='font-weight-normal'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  visibility_conditions=''  css_class='' ]"} /-->

<!-- wp:blockstrap/blockstrap-widget-nav-item {"text":"Contact Us","link_bg":"gray","text_color":"gray-dark","font_weight":"font-weight-normal","content":"\u003ca href=\u0022#http://handylist.local\u0022 class=\u0022nav-link link-gray-dark fw-normal\u0022 \u003eContact Us\u003c/a\u003e","sd_shortcode":"[bs_nav_item type='home'  page_id=''  post_id=''  taxonomy=''  term_id=''  custom_url=''  text='Contact Us'  icon_class=''  icon_aria_label=''  link_new_window='false'  link_nofollow='false'  link_attributes=''  link_type=''  link_size=''  link_bg='gray'  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg=''  link_pr_lg=''  link_pb_lg=''  link_pl_lg=''  link_divider=''  text_color='gray-dark'  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight='font-weight-normal'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  visibility_conditions=''  css_class='' ]"} /--></ul></div>
<!-- /wp:blockstrap/blockstrap-widget-nav --></div>
<!-- /wp:blockstrap/blockstrap-widget-container -->

<!-- wp:blockstrap/blockstrap-widget-container {"container":"col","col":"12","col_md":"6","col_lg":"3","text_color":"dark","mb_lg":"","content":"","sd_shortcode":"[bs_container container='col'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col='12'  col_md='6'  col_lg='3'  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_on_text='false'  text_color='dark'  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]","sd_shortcode_close":"[/bs_container]","className":"block-1618467995"} -->
<div class="wp-block-blockstrap-blockstrap-widget-container col-12 col-md-6 col-lg-3 bg-image-fixed text-dark col"><!-- wp:heading {"style":{"typography":{"fontStyle":"normal","fontWeight":"700"},"elements":{"link":{"color":{"text":"var:preset|color|gray-dark"}}}},"textColor":"gray-dark","fontSize":"medium"} -->
<h2 class="wp-block-heading has-gray-dark-color has-text-color has-link-color has-medium-font-size" style="font-style:normal;font-weight:700"><strong><strong>Legal</strong></strong></h2>
<!-- /wp:heading -->

<!-- wp:blockstrap/blockstrap-widget-nav {"inside_navbar":"0","flex_direction":"flex-column","font_size":"fs-5","mr_lg":"","ml_lg":"n3","pl_lg":"0","sd_shortcode":"[bs_nav anchor=''  inside_navbar='0'  container=''  flex_direction='flex-column'  nav_style=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  nav_fill=''  font_size='fs-5'  font_size_custom=''  bg=''  mt=''  mr='auto'  mb=''  ml='auto'  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg='n3'  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg='0'  border=''  rounded=''  rounded_size=''  shadow=''  width=''  css_class='' ]","sd_shortcode_close":"[/bs_nav]"} -->
<div class="wp-block-blockstrap-blockstrap-widget-nav blockstrap-nav" id="navbarNav_"><ul class="wp-block-blockstrap-blockstrap-widget-nav nav me-auto ms-auto ms-lg-n3 ps-0 flex-column fs-5"><!-- wp:blockstrap/blockstrap-widget-nav-item {"text":"Terms \u0026 Services","text_color":"gray-dark","font_weight":"font-weight-normal","content":"\u003ca href=\u0022#http://handylist.local\u0022 class=\u0022nav-link link-gray-dark fw-normal\u0022 \u003eTerms \u0026amp; Services\u003c/a\u003e","sd_shortcode":"[bs_nav_item type='home'  page_id=''  post_id=''  taxonomy=''  term_id=''  custom_url=''  text='Terms \u0026 Services'  icon_class=''  icon_aria_label=''  link_new_window='false'  link_nofollow='false'  link_attributes=''  link_type=''  link_size=''  link_bg=''  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg=''  link_pr_lg=''  link_pb_lg=''  link_pl_lg=''  link_divider=''  text_color='gray-dark'  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight='font-weight-normal'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  visibility_conditions=''  css_class='' ]"} /-->

<!-- wp:blockstrap/blockstrap-widget-nav-item {"text":"Privacy Policy","text_color":"gray-dark","font_weight":"font-weight-normal","content":"\u003ca href=\u0022#http://handylist.local\u0022 class=\u0022nav-link link-gray-dark fw-normal\u0022 \u003ePrivacy Policy\u003c/a\u003e","sd_shortcode":"[bs_nav_item type='home'  page_id=''  post_id=''  taxonomy=''  term_id=''  custom_url=''  text='Privacy Policy'  icon_class=''  icon_aria_label=''  link_new_window='false'  link_nofollow='false'  link_attributes=''  link_type=''  link_size=''  link_bg=''  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg=''  link_pr_lg=''  link_pb_lg=''  link_pl_lg=''  link_divider=''  text_color='gray-dark'  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight='font-weight-normal'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  visibility_conditions=''  css_class='' ]"} /--></ul></div>
<!-- /wp:blockstrap/blockstrap-widget-nav --></div>
<!-- /wp:blockstrap/blockstrap-widget-container -->

<!-- wp:blockstrap/blockstrap-widget-container {"container":"col","col":"12","col_md":"6","col_lg":"6","bg_on_text":true,"text_color":"white","mb_lg":"","pt":"3","pt_lg":"0","sd_shortcode":"[bs_container container='col'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col='12'  col_md='6'  col_lg='6'  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_on_text='true'  text_color='white'  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt='3'  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg='0'  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]","sd_shortcode_close":"[/bs_container]","className":"block-1618467995"} -->
<div class="wp-block-blockstrap-blockstrap-widget-container pt-3 pt-lg-0 col-12 col-md-6 col-lg-6 bg-image-fixed text-white col"><!-- wp:image {"id":5555,"width":"232px","height":"auto","sizeSlug":"full","linkDestination":"none"} -->
<figure class="wp-block-image size-full is-resized"><img src="<?php echo esc_url( $logo_url ); ?>" alt="" class="wp-image-5555" style="width:232px;height:auto"/></figure>
<!-- /wp:image -->

<!-- wp:blockstrap/blockstrap-widget-heading {"text":"Showcase trusted local tradespeople with HandyList, a home repair service directory featuring reviews, specialties, and contact details.","html_tag":"p","text_color":"gray-dark","font_size":"fs-5","font_weight":"font-weight-normal","mb_lg":"2"} -->
<p class="wp-block-blockstrap-blockstrap-widget-heading mb-2 text-gray-dark font-weight-normal fs-5">Showcase trusted local tradespeople with HandyList, a home repair service directory featuring reviews, specialties, and contact details.</p>
<!-- /wp:blockstrap/blockstrap-widget-heading -->

<!-- wp:blockstrap/blockstrap-widget-nav {"anchor":"contact-nav","inside_navbar":"0","font_size":"fs-5","mr_lg":"","ml_lg":"","sd_shortcode":"[bs_nav anchor='contact-nav'  inside_navbar='0'  container=''  flex_direction=''  nav_style=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  nav_fill=''  font_size='fs-5'  font_size_custom=''  bg=''  mt=''  mr='auto'  mb=''  ml='auto'  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  width=''  css_class='' ]","sd_shortcode_close":"[/bs_nav]"} -->
<div class="wp-block-blockstrap-blockstrap-widget-nav blockstrap-nav" id="navbarNav_contact-nav"><ul class="wp-block-blockstrap-blockstrap-widget-nav nav me-auto ms-auto fs-5"><!-- wp:blockstrap/blockstrap-widget-nav-item {"text":"info@ayecode.io","icon_class":"far fa-envelope","link_bg":"white","text_color":"gray-dark","font_weight":"font-weight-normal","content":"\u003ca href=\u0022#http://handylist.local\u0022 class=\u0022nav-link link-gray-dark fw-normal\u0022 \u003e\u003ci class=\u0022far fa-envelope me-2\u0022\u003e\u003c/i\u003einfo@ayecode.io\u003c/a\u003e","sd_shortcode":"[bs_nav_item type='home'  page_id=''  post_id=''  taxonomy=''  term_id=''  custom_url=''  text='info@ayecode.io'  icon_class='far fa-envelope'  icon_aria_label=''  link_new_window='false'  link_nofollow='false'  link_attributes=''  link_type=''  link_size=''  link_bg='white'  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg=''  link_pr_lg=''  link_pb_lg=''  link_pl_lg=''  link_divider=''  text_color='gray-dark'  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight='font-weight-normal'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  visibility_conditions=''  css_class='' ]"} /-->

<!-- wp:blockstrap/blockstrap-widget-nav-item {"text":"+123 456 789","icon_class":"fa-solid fa-mobile-screen","link_bg":"white","text_color":"gray-dark","font_weight":"font-weight-normal","content":"\u003ca href=\u0022#http://handylist.local\u0022 class=\u0022nav-link link-gray-dark fw-normal\u0022 \u003e\u003ci class=\u0022fa-solid fa-mobile-screen me-2\u0022\u003e\u003c/i\u003e+123 456 789\u003c/a\u003e","sd_shortcode":"[bs_nav_item type='home'  page_id=''  post_id=''  taxonomy=''  term_id=''  custom_url=''  text='+123 456 789'  icon_class='fa-solid fa-mobile-screen'  icon_aria_label=''  link_new_window='false'  link_nofollow='false'  link_attributes=''  link_type=''  link_size=''  link_bg='white'  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg=''  link_pr_lg=''  link_pb_lg=''  link_pl_lg=''  link_divider=''  text_color='gray-dark'  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight='font-weight-normal'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  visibility_conditions=''  css_class='' ]"} /--></ul></div>
<!-- /wp:blockstrap/blockstrap-widget-nav --></div>
<!-- /wp:blockstrap/blockstrap-widget-container --></div>
<!-- /wp:blockstrap/blockstrap-widget-container -->

<!-- wp:blockstrap/blockstrap-widget-container {"container":"row","mt_lg":"1","mb_lg":"","pt_lg":"4","sd_shortcode":"[bs_container container='row'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg='1'  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg='4'  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]","sd_shortcode_close":"[/bs_container]","className":"border-top border-gray-dark"} -->
<div class="wp-block-blockstrap-blockstrap-widget-container mt-1 pt-4 bg-image-fixed row"><!-- wp:blockstrap/blockstrap-widget-container {"container":"col","text_align_lg":"text-lg-center","sd_shortcode":"[bs_container container='col'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg='text-lg-center'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg='3'  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]","sd_shortcode_close":"[/bs_container]","className":"block-1618467995"} -->
<div class="wp-block-blockstrap-blockstrap-widget-container mb-3 bg-image-fixed text-center col"><!-- wp:blockstrap/blockstrap-widget-nav {"anchor":"social-nav","inside_navbar":"0","flex_justify_content_lg":"justify-content-lg-center","font_size":"fs-5","mr_lg":"","ml_lg":"","sd_shortcode":"[bs_nav anchor='social-nav'  inside_navbar='0'  container=''  flex_direction=''  nav_style=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg='justify-content-lg-center'  nav_fill=''  font_size='fs-5'  font_size_custom=''  bg=''  mt=''  mr='auto'  mb=''  ml='auto'  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  width=''  css_class='' ]","sd_shortcode_close":"[/bs_nav]"} -->
<div class="wp-block-blockstrap-blockstrap-widget-nav blockstrap-nav" id="navbarNav_social-nav"><ul class="wp-block-blockstrap-blockstrap-widget-nav nav me-auto ms-auto fs-5 justify-content-center"><!-- wp:blockstrap/blockstrap-widget-nav-item {"type":"custom","custom_url":"#facebook","icon_class":"fab fa-facebook","link_bg":"white","text_color":"gray-dark","content":"\u003ca href=\u0022##facebook\u0022 class=\u0022nav-link link-gray-dark \u0022 \u003e\u003ci class=\u0022fab fa-facebook\u0022\u003e\u003c/i\u003e\u003c/a\u003e","sd_shortcode":"[bs_nav_item type='custom'  page_id=''  post_id=''  taxonomy=''  term_id=''  custom_url='#facebook'  text=''  icon_class='fab fa-facebook'  icon_aria_label=''  link_new_window='false'  link_nofollow='false'  link_attributes=''  link_type=''  link_size=''  link_bg='white'  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg=''  link_pr_lg=''  link_pb_lg=''  link_pl_lg=''  link_divider=''  text_color='gray-dark'  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  visibility_conditions=''  css_class='' ]"} /-->

<!-- wp:blockstrap/blockstrap-widget-nav-item {"type":"custom","custom_url":"#twriiter","icon_class":"fab fa-twitter","link_bg":"white","text_color":"gray-dark","content":"\u003ca href=\u0022##twriiter\u0022 class=\u0022nav-link link-gray-dark \u0022 \u003e\u003ci class=\u0022fab fa-twitter\u0022\u003e\u003c/i\u003e\u003c/a\u003e","sd_shortcode":"[bs_nav_item type='custom'  page_id=''  post_id=''  taxonomy=''  term_id=''  custom_url='#twriiter'  text=''  icon_class='fab fa-twitter'  icon_aria_label=''  link_new_window='false'  link_nofollow='false'  link_attributes=''  link_type=''  link_size=''  link_bg='white'  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg=''  link_pr_lg=''  link_pb_lg=''  link_pl_lg=''  link_divider=''  text_color='gray-dark'  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  visibility_conditions=''  css_class='' ]"} /-->

<!-- wp:blockstrap/blockstrap-widget-nav-item {"type":"custom","custom_url":"#instagram","icon_class":"fab fa-instagram","link_bg":"white","text_color":"gray-dark","content":"\u003ca href=\u0022##instagram\u0022 class=\u0022nav-link link-gray-dark \u0022 \u003e\u003ci class=\u0022fab fa-instagram\u0022\u003e\u003c/i\u003e\u003c/a\u003e","sd_shortcode":"[bs_nav_item type='custom'  page_id=''  post_id=''  taxonomy=''  term_id=''  custom_url='#instagram'  text=''  icon_class='fab fa-instagram'  icon_aria_label=''  link_new_window='false'  link_nofollow='false'  link_attributes=''  link_type=''  link_size=''  link_bg='white'  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg=''  link_pr_lg=''  link_pb_lg=''  link_pl_lg=''  link_divider=''  text_color='gray-dark'  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  visibility_conditions=''  css_class='' ]"} /--></ul></div>
<!-- /wp:blockstrap/blockstrap-widget-nav -->

<!-- wp:blockstrap/blockstrap-widget-heading {"text":"Copyright © BlockStrap 2022. All rights reserved.","html_tag":"p","text_color":"gray-dark","font_size":"fs-6","font_weight":"font-weight-normal","mb_lg":"2"} -->
<p class="wp-block-blockstrap-blockstrap-widget-heading mb-2 text-gray-dark font-weight-normal fs-6">Copyright © BlockStrap 2022. All rights reserved.</p>
<!-- /wp:blockstrap/blockstrap-widget-heading --></div>
<!-- /wp:blockstrap/blockstrap-widget-container --></div>
<!-- /wp:blockstrap/blockstrap-widget-container --></div>
<!-- /wp:blockstrap/blockstrap-widget-container --></div>
<!-- /wp:blockstrap/blockstrap-widget-container -->