<?php
/**
 * Title: HandyList - Default Header
 * Slug: handylist/header-default
 * Categories: blockstrap-site-header
 * Viewport Width: 1280
 */

 $logo_url = esc_url( get_theme_file_uri( 'assets/images/logo-white.svg' ) ); /* <?php echo esc_url( $logo_url ); ?> */

?>

<!-- wp:blockstrap/blockstrap-widget-skip-links {"content":"\u003ca href=\u0022#main\u0022 class=\u0022btn btn-primary\u0022\u003eSkip to main content\u003c/a\u003e","sd_shortcode":"[bs_skip_links text1='Skip to main content'  hash1='main'  text2=''  hash2=''  text3=''  hash3=''  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  css_class='' ]"} /-->

<!-- wp:blockstrap/blockstrap-widget-container {"container":"container-fluid","bg_color":"rgba(0,0,0,0.2)","mb_lg":"","pr_lg":"0","pl_lg":"0","border":"0","border_type":"border","position":"fixed-top","content":"\u003ca href=\u0022#main\u0022 class=\u0022btn btn-primary\u0022\u003eSkip to main content\u003c/a\u003e","sd_shortcode":"[bs_container container='container-fluid'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='rgba(0,0,0,0.2)'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg='0'  pb_lg=''  pl_lg='0'  border='0'  border_type='border'  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position='fixed-top'  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]","sd_shortcode_close":"[/bs_container]"} -->
<div class="wp-block-blockstrap-blockstrap-widget-container pe-0 ps-0 border-0 bg-image-fixed container-fluid fixed-top border"><!-- wp:blockstrap/blockstrap-widget-navbar {"bg":"custom-color","bg_color":"rgba(30,106,101,0.8)","bgtus":true,"container":"navbar-dark","inner_container":"container","mb_lg":"","pr":"2","pl":"2","pt_lg":"4","pb_lg":"4","border":"0","rounded_size":"0","sd_shortcode":"[bs_navbar bg='custom-color'  bg_color='rgba(30,106,101,0.8)'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bgtus='true'  cscos='false'  container='navbar-dark'  inner_container='container'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr='2'  pb=''  pl='2'  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg='4'  pr_lg=''  pb_lg='4'  pl_lg=''  border='0'  rounded=''  rounded_size='0'  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom='' ]","sd_shortcode_close":"[/bs_navbar]"} -->
<nav class="navbar navbar-expand-lg pe-2 ps-2 pt-4 pb-4 border-0 rounded-0 bg-custom-color bg-image-fixed bg-transparent-until-scroll navbar-dark" style="background-color:rgba(30,106,101,0.8)"><div class="wp-block-blockstrap-blockstrap-widget-navbar container"><!-- wp:blockstrap/blockstrap-widget-navbar-brand {"text":"","icon_image":"<?php echo esc_url( $logo_url ); ?>","img_max_width":160,"type":"custom","custom_url":"/","brand_font_size":"h1","brand_font_weight":"font-weight-normal","brand_font_italic":"font-italic","text_align_lg":"text-lg-center","bg_gradient":"linear-gradient(135deg,rgb(34,227,7) 0%,rgb(245,245,245) 100%)","bg_on_text":true,"mr_lg":"4","mb_lg":"","rounded_size":"lg","sd_shortcode":"[bs_navbar_brand text=''  icon_image='<?php echo esc_url( $logo_url ); ?>'  img_max_width='160'  type='custom'  custom_url='/'  text_color=''  brand_font_size='h1'  brand_font_weight='font-weight-normal'  brand_font_italic='font-italic'  text_justify='false'  text_align=''  text_align_md=''  text_align_lg='text-lg-center'  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgb(34,227,7) 0%,rgb(245,245,245) 100%)'  bg_on_text='true'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg='4'  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size='lg'  shadow=''  css_class='' ]"} -->
<a class="navbar-brand d-flex align-items-center me-4 rounded-lg text-center" href="/"><img class="" alt="Site logo" src="<?php echo esc_url( $logo_url ); ?>" style="max-width:160px" width="160" height="50"/><span class="mb-0 props.attributes.brand_font_size props.attributes.brand_font_weight fst-italic"></span></a>
<!-- /wp:blockstrap/blockstrap-widget-navbar-brand -->

<!-- wp:blockstrap/blockstrap-widget-nav {"anchor":"main-nav","inside_navbar":"0","font_size":"fs-6","mr":"","ml":"","mr_lg":"","ml_lg":"","rounded_size":"lg","width":"w-100","sd_shortcode":"[bs_nav anchor='main-nav'  inside_navbar='0'  container=''  flex_direction=''  nav_style=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  nav_fill=''  font_size='fs-6'  font_size_custom=''  bg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size='lg'  shadow=''  width='w-100'  css_class='' ]","sd_shortcode_close":"[/bs_nav]"} -->
<div class="wp-block-blockstrap-blockstrap-widget-nav blockstrap-nav" id="navbarNav_main-nav"><ul class="wp-block-blockstrap-blockstrap-widget-nav nav rounded-lg w-100 fs-6"><!-- wp:blockstrap/blockstrap-widget-nav-item {"type":"offcanvas","page_id":"4426","custom_url":"#main-menu","icon_class":"fa-solid fa-bars-staggered","link_size":"large","link_bg":"white","link_pr":"0","text_color":"white","font_weight":"font-weight-bold","border":"0","rounded":"rounded","rounded_size":"2","content":"\u003ca href=\u0022##main-menu\u0022 class=\u0022nav-link link-white pe-0 fw-bold\u0022  data-bs-toggle=\u0022offcanvas\u0022 \u003e\u003ci class=\u0022fa-solid fa-bars-staggered\u0022\u003e\u003c/i\u003e\u003c/a\u003e","sd_shortcode":"[bs_nav_item type='offcanvas'  page_id='4426'  post_id=''  taxonomy=''  term_id=''  custom_url='#main-menu'  text=''  icon_class='fa-solid fa-bars-staggered'  icon_aria_label=''  link_new_window='false'  link_nofollow='false'  link_attributes=''  link_type=''  link_size='large'  link_bg='white'  link_pt=''  link_pr='0'  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg=''  link_pr_lg=''  link_pb_lg=''  link_pl_lg=''  link_divider=''  text_color='white'  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight='font-weight-bold'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border='0'  rounded='rounded'  rounded_size='2'  shadow=''  visibility_conditions=''  css_class='' ]"} /--></ul></div>
<!-- /wp:blockstrap/blockstrap-widget-nav --></div></nav>
<!-- /wp:blockstrap/blockstrap-widget-navbar --></div>
<!-- /wp:blockstrap/blockstrap-widget-container -->

<!-- wp:blockstrap/blockstrap-widget-offcanvas {"open_with":"external","anchor":"main-menu","button_text":"Open Menu","offcanvas_position":"end","header_title":"","styleid":"block-nwvwxnfonm","sd_shortcode":"[bs_offcanvas open_with='external'  anchor='main-menu'  button_text='Open Menu'  width=''  width_md=''  width_lg=''  height=''  height_md=''  height_lg=''  offcanvas_position='end'  static_backdrop=''  header_hide=''  header_title=''  close_icon=''  link_type='btn'  link_size=''  link_bg='primary'  header_text_color=''  header_font_size='fs-5'  header_font_weight=''  header_bg=''  body_bg=''  body_pt=''  body_pr=''  body_pb=''  body_pl=''  border=''  rounded=''  rounded_size=''  shadow='shadow'  visibility_conditions=''  css_class=''  styleid='block-nwvwxnfonm' ]","sd_shortcode_close":"[/bs_offcanvas]"} -->
<div class="wp-block-blockstrap-blockstrap-widget-offcanvas alert alert-info">Offcanvas Placeholder for #main-menu</div><div id="main-menu" class="offcanvas  offcanvas-end shadow block-nwvwxnfonm" style="z-index:100000" tabindex="-1" data-bs-backdrop="true" data-bs-keyboard="true"><div class="offcanvas-header  "><h1 class="offcanvas-title  fs-5"></h1><button class="btn-close bg-white" data-bs-dismiss="offcanvas" aria-label="Close"></button></div><div class="offcanvas-body  "><div class="wp-block-blockstrap-blockstrap-widget-offcanvas"><!-- wp:blockstrap/blockstrap-widget-navbar {"bg":"white","bg_color":"rgba(255,255,255,0.84)","inner_container":"container","mb_lg":"","pt_lg":"4","pb_lg":"4","border":"0","sd_shortcode":"[bs_navbar bg='white'  bg_color='rgba(255,255,255,0.84)'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bgtus='false'  cscos='false'  container=''  inner_container='container'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg='4'  pr_lg=''  pb_lg='4'  pl_lg=''  border='0'  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom='' ]","sd_shortcode_close":"[/bs_navbar]"} -->
<nav class="navbar navbar-expand-lg pt-4 pb-4 border-0 bg-white bg-image-fixed"><div class="wp-block-blockstrap-blockstrap-widget-navbar container"><!-- wp:blockstrap/blockstrap-widget-nav {"anchor":"main-nav","inside_navbar":"0","flex_direction":"flex-column","font_size":"fs-4","mr":"","ml":"","ml_lg":"0","pr_lg":"0","pl_lg":"0","rounded_size":"lg","width":"w-100","sd_shortcode":"[bs_nav anchor='main-nav'  inside_navbar='0'  container=''  flex_direction='flex-column'  nav_style=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  nav_fill=''  font_size='fs-4'  font_size_custom=''  bg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg='0'  mb_lg=''  ml_lg='0'  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg='0'  pb_lg=''  pl_lg='0'  border=''  rounded=''  rounded_size='lg'  shadow=''  width='w-100'  css_class='' ]","sd_shortcode_close":"[/bs_nav]"} -->
<div class="wp-block-blockstrap-blockstrap-widget-nav blockstrap-nav" id="navbarNav_main-nav"><ul class="wp-block-blockstrap-blockstrap-widget-nav nav me-0 ms-0 pe-0 ps-0 rounded-lg flex-column w-100 fs-4"><!-- wp:blockstrap/blockstrap-widget-nav-item {"type":"gd_place","page_id":"1858","custom_url":"#about","text":"Browse","link_size":"large","link_pl_lg":"0","text_color":"dark","font_weight":"font-weight-bold","pl_lg":"0","content":"\u003ca href=\u0022#http://handylist.local/place/\u0022 class=\u0022nav-link link-dark ps-0 fw-bold\u0022 \u003eBrowse\u003c/a\u003e","sd_shortcode":"[bs_nav_item type='gd_place'  page_id='1858'  post_id=''  taxonomy=''  term_id=''  custom_url='#about'  text='Browse'  icon_class=''  icon_aria_label=''  link_new_window='false'  link_nofollow='false'  link_attributes=''  link_type=''  link_size='large'  link_bg=''  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg=''  link_pr_lg=''  link_pb_lg=''  link_pl_lg='0'  link_divider=''  text_color='dark'  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight='font-weight-bold'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg='0'  border=''  rounded=''  rounded_size=''  shadow=''  visibility_conditions=''  css_class='' ]"} /-->

<!-- wp:blockstrap/blockstrap-widget-nav-item {"type":"gd_search","custom_url":"#","text":"Search","link_pl_lg":"0","text_color":"dark","font_weight":"font-weight-bold","pl_lg":"0","content":"\u003ca href=\u0022#http://handylist.local/search/\u0022 class=\u0022nav-link link-dark ps-0 fw-bold\u0022 \u003eSearch\u003c/a\u003e","sd_shortcode":"[bs_nav_item type='gd_search'  page_id=''  post_id=''  taxonomy=''  term_id=''  custom_url='#'  text='Search'  icon_class=''  icon_aria_label=''  link_new_window='false'  link_nofollow='false'  link_attributes=''  link_type=''  link_size=''  link_bg=''  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg=''  link_pr_lg=''  link_pb_lg=''  link_pl_lg='0'  link_divider=''  text_color='dark'  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight='font-weight-bold'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg='0'  border=''  rounded=''  rounded_size=''  shadow=''  visibility_conditions=''  css_class='' ]"} /-->

<!-- wp:blockstrap/blockstrap-widget-nav-item {"type":"page","page_id":"3336","custom_url":"#","text":"Blog","link_pl_lg":"0","text_color":"dark","font_weight":"font-weight-bold","pl_lg":"0","content":"\u003ca href=\u0022#http://handylist.local/blog/\u0022 class=\u0022nav-link link-dark ps-0 fw-bold\u0022 \u003eBlog\u003c/a\u003e","sd_shortcode":"[bs_nav_item type='page'  page_id='3336'  post_id=''  taxonomy=''  term_id=''  custom_url='#'  text='Blog'  icon_class=''  icon_aria_label=''  link_new_window='false'  link_nofollow='false'  link_attributes=''  link_type=''  link_size=''  link_bg=''  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg=''  link_pr_lg=''  link_pb_lg=''  link_pl_lg='0'  link_divider=''  text_color='dark'  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight='font-weight-bold'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg='0'  border=''  rounded=''  rounded_size=''  shadow=''  visibility_conditions=''  css_class='' ]"} /-->

<!-- wp:blockstrap/blockstrap-widget-nav-item {"type":"page","page_id":"1858","custom_url":"#","text":"Contact","link_pl_lg":"0","text_color":"dark","font_weight":"font-weight-bold","mb_lg":"3","pl_lg":"0","content":"\u003ca href=\u0022#http://handylist.local/contact/\u0022 class=\u0022nav-link link-dark ps-0 fw-bold\u0022 \u003eContact\u003c/a\u003e","sd_shortcode":"[bs_nav_item type='page'  page_id='1858'  post_id=''  taxonomy=''  term_id=''  custom_url='#'  text='Contact'  icon_class=''  icon_aria_label=''  link_new_window='false'  link_nofollow='false'  link_attributes=''  link_type=''  link_size=''  link_bg=''  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg=''  link_pr_lg=''  link_pb_lg=''  link_pl_lg='0'  link_divider=''  text_color='dark'  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight='font-weight-bold'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg='3'  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg='0'  border=''  rounded=''  rounded_size=''  shadow=''  visibility_conditions=''  css_class='' ]"} /-->

<!-- wp:separator {"align":"center","className":"is-style-wide","style":{"color":{"background":"#dddfdf"}}} -->
<hr class="wp-block-separator aligncenter has-text-color has-alpha-channel-opacity has-background is-style-wide" style="background-color:#dddfdf;color:#dddfdf"/>
<!-- /wp:separator -->

<!-- wp:blockstrap/blockstrap-widget-nav-item {"type":"page","page_id":"5238","text":"Dashboard","link_pl_lg":"0","font_weight":"font-weight-bold","mt_lg":"3","visibility_conditions":"{\u0022rule1\u0022:{\u0022type\u0022:\u0022logged_out\u0022},\u0022output\u0022:{\u0022type\u0022:\u0022hide\u0022}}","content":"\u003ca href=\u0022#http://handylist.local/account/\u0022 class=\u0022nav-link ps-0 fw-bold\u0022 \u003eDashboard\u003c/a\u003e","sd_shortcode":"[bs_nav_item type='page'  page_id='5238'  post_id=''  taxonomy=''  term_id=''  custom_url=''  text='Dashboard'  icon_class=''  icon_aria_label=''  link_new_window='false'  link_nofollow='false'  link_attributes=''  link_type=''  link_size=''  link_bg=''  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg=''  link_pr_lg=''  link_pb_lg=''  link_pl_lg='0'  link_divider=''  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight='font-weight-bold'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg='3'  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  visibility_conditions='{\u0022rule1\u0022:{\u0022type\u0022:\u0022logged_out\u0022},\u0022output\u0022:{\u0022type\u0022:\u0022hide\u0022}}'  css_class='' ]"} /-->

<!-- wp:blockstrap/blockstrap-widget-nav-item {"type":"page","page_id":"5242","text":"Profile","link_pl_lg":"0","font_weight":"font-weight-bold","visibility_conditions":"{\u0022rule1\u0022:{\u0022type\u0022:\u0022logged_out\u0022},\u0022output\u0022:{\u0022type\u0022:\u0022hide\u0022}}","content":"\u003ca href=\u0022#http://handylist.local/profile/\u0022 class=\u0022nav-link ps-0 fw-bold\u0022 \u003eProfile\u003c/a\u003e","sd_shortcode":"[bs_nav_item type='page'  page_id='5242'  post_id=''  taxonomy=''  term_id=''  custom_url=''  text='Profile'  icon_class=''  icon_aria_label=''  link_new_window='false'  link_nofollow='false'  link_attributes=''  link_type=''  link_size=''  link_bg=''  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg=''  link_pr_lg=''  link_pb_lg=''  link_pl_lg='0'  link_divider=''  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight='font-weight-bold'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  visibility_conditions='{\u0022rule1\u0022:{\u0022type\u0022:\u0022logged_out\u0022},\u0022output\u0022:{\u0022type\u0022:\u0022hide\u0022}}'  css_class='' ]"} /-->

<!-- wp:blockstrap/blockstrap-widget-nav-item {"type":"page","page_id":"5237","text":"Login","link_pl_lg":"0","font_weight":"font-weight-bold","visibility_conditions":"{\u0022rule1\u0022:{\u0022type\u0022:\u0022logged_in\u0022},\u0022output\u0022:{\u0022type\u0022:\u0022hide\u0022}}","content":"\u003ca href=\u0022#http://handylist.local/login/\u0022 class=\u0022nav-link ps-0 fw-bold\u0022 \u003eLogin\u003c/a\u003e","sd_shortcode":"[bs_nav_item type='page'  page_id='5237'  post_id=''  taxonomy=''  term_id=''  custom_url=''  text='Login'  icon_class=''  icon_aria_label=''  link_new_window='false'  link_nofollow='false'  link_attributes=''  link_type=''  link_size=''  link_bg=''  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg=''  link_pr_lg=''  link_pb_lg=''  link_pl_lg='0'  link_divider=''  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight='font-weight-bold'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  visibility_conditions='{\u0022rule1\u0022:{\u0022type\u0022:\u0022logged_in\u0022},\u0022output\u0022:{\u0022type\u0022:\u0022hide\u0022}}'  css_class='' ]"} /-->

<!-- wp:blockstrap/blockstrap-widget-nav-item {"type":"page","page_id":"5236","text":"Register","link_pl_lg":"0","font_weight":"font-weight-bold","pl_lg":"0","visibility_conditions":"{\u0022rule1\u0022:{\u0022type\u0022:\u0022logged_in\u0022},\u0022output\u0022:{\u0022type\u0022:\u0022hide\u0022}}","content":"\u003ca href=\u0022#http://handylist.local/register/\u0022 class=\u0022nav-link ps-0 fw-bold\u0022 \u003eRegister\u003c/a\u003e","sd_shortcode":"[bs_nav_item type='page'  page_id='5236'  post_id=''  taxonomy=''  term_id=''  custom_url=''  text='Register'  icon_class=''  icon_aria_label=''  link_new_window='false'  link_nofollow='false'  link_attributes=''  link_type=''  link_size=''  link_bg=''  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg=''  link_pr_lg=''  link_pb_lg=''  link_pl_lg='0'  link_divider=''  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight='font-weight-bold'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg='0'  border=''  rounded=''  rounded_size=''  shadow=''  visibility_conditions='{\u0022rule1\u0022:{\u0022type\u0022:\u0022logged_in\u0022},\u0022output\u0022:{\u0022type\u0022:\u0022hide\u0022}}'  css_class='' ]"} /-->

<!-- wp:blockstrap/blockstrap-widget-nav-item {"type":"page","page_id":"4426","text":"Join as a Contractor","link_bg":"primary","link_pl_lg":"0","font_weight":"font-weight-bold","pl_lg":"0","content":"\u003ca href=\u0022#http://handylist.local/add-listing/\u0022 class=\u0022nav-link ps-0 fw-bold\u0022 \u003eJoin as a Contractor\u003c/a\u003e","sd_shortcode":"[bs_nav_item type='page'  page_id='4426'  post_id=''  taxonomy=''  term_id=''  custom_url=''  text='Join as a Contractor'  icon_class=''  icon_aria_label=''  link_new_window='false'  link_nofollow='false'  link_attributes=''  link_type=''  link_size=''  link_bg='primary'  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg=''  link_pr_lg=''  link_pb_lg=''  link_pl_lg='0'  link_divider=''  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight='font-weight-bold'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg='0'  border=''  rounded=''  rounded_size=''  shadow=''  visibility_conditions=''  css_class='' ]"} /--></ul></div>
<!-- /wp:blockstrap/blockstrap-widget-nav --></div></nav>
<!-- /wp:blockstrap/blockstrap-widget-navbar --></div></div></div>
<!-- /wp:blockstrap/blockstrap-widget-offcanvas -->